spring.application.name=demo

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/thecleartrade_db
spring.datasource.username=postgres
spring.datasource.password=password123

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
